FROM resin/%%RESIN_MACHINE_NAME%%-python

# Set our working directory
WORKDIR /nickbox

COPY ./requirements.txt /nickbox/requirements.txt

RUN pip install -r requirements.txt

ENV INITSYSTEM on
COPY nickbox.service /etc/systemd/system/nickbox.service
RUN systemctl enable /etc/systemd/system/nickbox.service
